name: validation

on:
  push:
    branches: [get-sarted-wit-github-actions]
  pull_request:
    branches: [get-sarted-wit-github-actions]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout repository
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run test
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout repository
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run test -- --coverage
      - uses: actions/upload-artifact@v3
        name: archve coverage report
        with:
          name: coverage-report
          path: coverage
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run build
# TODO: build artefact for assets
